# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "openai",
#     "polib",
# ]
# ///

import polib
import re

from openai import OpenAI
client = OpenAI()

def log_completion_result(prompt: str, response: str, filename: str = "completions.txt"):
    with open(filename, "a", encoding="utf-8") as f:
        f.write("=== PROMPT ===\n")
        f.write(prompt + "\n")
        f.write("=== RESPONSE ===\n")
        f.write(response + "\n\n")

def mask_tags(text: str) -> tuple[str, list[str]]:
    """
    Converts tags like:
      [item]item_id_with_no_spaces[/item]  -> __1_ITEM_ID_WITH_NO_SPACES__
      [reputation=high]     -> __2_REPUTATION_HIGH__
      [/reputation]         -> __3_REPUTATION_CLOSE__
    and records original content in mapping.
    """
    mapping: list[str] = []

    def make_identifier(tag: str, inner: str | None = None, attr: str | None = None, closing: bool = False) -> str:
        if closing:
            base = f"{tag}_CLOSE"
        elif inner:
            base = f"{tag}_{inner}"
        elif attr:
            base = f"{tag}_{attr.lstrip('=')}"
        else:
            base = tag
        # sanitize: keep letters/numbers/underscore, collapse multiple underscores, uppercase
        ident = re.sub(r'[^0-9A-Za-z]+', '_', base)
        ident = re.sub(r'_+', '_', ident).strip('_').upper() or 'TAG'
        return ident

    # match [tag]inner[/tag], [tag=...]inner[/tag] with [a-zA-Z-_] in inner
    pattern_tags = re.compile(r'\[(\w+)(=[^\]]+)?\]([a-zA-Z-_]*?)\[/\1\]')
    def repl_tags(m: re.Match) -> str:
        tag = m.group(1)
        attr = m.group(2)
        inner = m.group(3)
        identifier = make_identifier(tag, inner=inner if inner else None, attr=attr, closing=False)
        mapping.append(m.group(0))
        return f"__{len(mapping)}_{identifier}__"
    text = pattern_tags.sub(repl_tags, text)

    # match [tag=...] and [/tag] separately
    pattern_reputation = re.compile(r'\[(\/?)(\w+)(=[^\]]+)?\]')
    def repl_reputation(m: re.Match) -> str:
        tag = m.group(2)
        attr = m.group(3)
        whole = m.group(0)
        
        closing = whole.startswith('[/')
        identifier = make_identifier(tag, inner=None, attr=attr, closing=closing)
        mapping.append(m.group(0))
        return f"__{len(mapping)}_{identifier}__"
    text = pattern_reputation.sub(repl_reputation, text)

    return (text, mapping)

def unmask_tags(text: str, mapping: list[str]) -> str:
    """
    Replaces placeholders like __1_ITEM_ID__ back to their original tag content using mapping.
    """
    def replacement(m: re.Match) -> str:
        index = int(m.group(1)) - 1
        if 0 <= index < len(mapping):
            return mapping[index]
        return m.group(0)


    pattern = re.compile(r'__([0-9]+)_[A-Z0-9_-]+__')
    
    # Repeatedly find and replace. We can't use `.sub` once... for some reason??
    while True:
        new_text = pattern.sub(replacement, text, 1)
        if new_text == text:
            break
        text = new_text
    
    return text

def translate_text(text: str, tl_desc: str, target_language: str):
    # Example call to GPT or translation API (this is a mock function)
    
    print(f"Translating {text}")
    
    response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=[
            {"role": "system", "content": f"You are a translation engine that translates text to {target_language} while preserving tags like __1_ITEM_MEANING__ and format specifiers. You do not respond with anything except the translated text."},
            {"role": "user", "content": f"The following text is \"{tl_desc}\". Translate the following text to {target_language}:\n\n{text}"}
        ]
    )
    
    translated = response.choices[0].message.content.strip()

    print(f"Translated to: {translated}")

    return translated
    
    # # Mock translation: replace non-tag words unlike __1_DO_NOT_CHANGE__ with dashes
    # def mock_translate_word(word: str) -> str:
    #     if re.match(r'__\d+_[A-Z0-9_]+__', word):
    #         return word
    #     elif re.match(r'\s+|%.', word):
    #         return word
    #     else:
    #         return '-' * len(word)
    
    # translated = ''.join(mock_translate_word(w) for w in re.findall(r'\S+|\s+', text))
    
    # # Temporary before I blow through $100 of API credits
    # # return f"[Translated as a \"{tl_desc}\" to {target_language}]: {translated}"
    # return translated

def create_po_file(translations: dict[str, tuple[str, str]], language: str):
    po = polib.POFile()
    po.header = "Autogenerated by localization/translate.py"
    po.metadata = {
        'Language': language,
        'Content-Type': 'text/plain; charset=utf-8',
    }

    for original, translated in translations.items():
        entry = polib.POEntry(
            msgid=original,
            msgstr=translated[0],
            msgctxt=translated[1]
        )
        po.append(entry)

    po.save(f'{language}.po')

def process_pot_file(pot_file_path, target_language):
    translations = {}
    
    pot_data = polib.pofile(pot_file_path)
    
    for entry in pot_data:
        line = entry.msgid
        
        if not line.strip():
            continue
        
        tl_desc = entry.comment if entry.comment else "general text"
        tl_desc = tl_desc.replace("TRANSLATORS: ", "")
        tl_desc = re.sub(r'\s+', ' ', tl_desc)
        tl_desc = tl_desc.strip()
        if entry.msgctxt:
            tl_desc += f" (Context: {entry.msgctxt})"
        
        (masked_line, mapping) = mask_tags(line)
        
        translated = translate_text(masked_line, tl_desc, target_language)
        
        final_translation = unmask_tags(translated, mapping)
        
        # print(f"Translated line: \"{line.strip()[:30]}\" to \"{final_translation.strip()[:30]}\"")
        
        translations[line] = (final_translation, entry.msgctxt)
    
    create_po_file(translations, target_language)

process_pot_file('template.pot', 'jp')
