@tool

extends TileMapLayer

class_name WorldInteractableTilemap

@export var automation_zones_tilemap: AutomationZonesTilemap
@export var automation_objects_tilemap: AutomationObjectsTilemap

@onready var interactables: Node2D = $WorldInteractables

@export_group("Tools", "tool_")
@export_tool_button("Add missing counter interactables") var tool_add_missing_counters = _add_missing_counters
@export_tool_button("Delete autogenerated interactables") var tool_delete_autogenerated = _delete_autogenerated
@export_tool_button("Correct all interactable positions") var tool_correct_interactables = _correct_interactables
@export_tool_button("Rebuild tiles") var tool_rebuild_tiles = _rebuild_tiles

var interactable_map: Dictionary[Vector2i, Node2D] = {}

func _ready():
    # Populate tile map with what's in the world so we can easily set things up in the editor;
    # future changes will be manually handled instead of from scratch
    
    _update_interactable_map()

func _update_interactable_map():
    interactable_map.clear()
    for child in interactables.get_children():
        interactable_map[_get_tilemap_pos(child.get_node("InteractableContent").global_position)] = child

func _get_tilemap_pos(global_pos: Vector2) -> Vector2i:
    return local_to_map(to_local(global_pos))

const TableSurfaceInteractable = preload("res://world/interactable/TableSurfaceInteractable.tscn")

func _correct_interactables():
    # Snap all interactables to the correct position in their cell
    for child in interactables.get_children():
        var content = child.get_node("InteractableContent")
        var cell = _get_tilemap_pos(content.global_position)
        var cell_data = automation_objects_tilemap.get_cell_tile_data(cell)
        if cell_data == null:
            push_warning("Interactable %s at %s is not on an automation object." % [child.name, str(cell)])
            continue
        
        var offset = Vector2(0, 3)
        var direction = cell_data.get_custom_data("facing")
        match direction:
            "up":
                offset = Vector2(0, 5)
            "left":
                offset = Vector2(0, 5)
            "right":
                offset = Vector2(0, 5)
        
        child.position = automation_objects_tilemap.map_to_local(cell) + offset

func _add_missing_counters():
    _update_interactable_map()

    # For every counter tile that doesn't have an interactable on it, add a blank counter one.
    for cell in automation_objects_tilemap.get_used_cells():
        var cell_data = automation_objects_tilemap.get_cell_tile_data(cell)
        if cell_data == null or cell_data.get_custom_data("meaning") != "counter":
            continue
        
        if interactable_map.has(cell):
            continue
        
        var counter_instance = TableSurfaceInteractable.instantiate()
        counter_instance.name = "!Counter_%d_%d" % [cell.x, cell.y]
        interactables.add_child(counter_instance)
        counter_instance.position = automation_objects_tilemap.map_to_local(cell)
        counter_instance.owner = get_tree().edited_scene_root
        interactable_map[cell] = counter_instance

func _delete_autogenerated():
    for child in interactables.get_children():
        if child.name.begins_with("!"):
            child.queue_free()
    
    _update_interactable_map.call_deferred()

func _rebuild_tiles():
    var start_time = Time.get_ticks_usec()
    
    _update_interactable_map()

    var update_interactable_map_time = Time.get_ticks_usec() - start_time
    start_time = Time.get_ticks_usec()

    # Clear all tiles in the automation zones
    var used_cells = automation_zones_tilemap.get_used_cells()

    # Clear all cells in automation zones, since we'll rebuild all of them
    for cell in used_cells:
        var zone_data = automation_zones_tilemap.get_cell_tile_data(cell)
        if not zone_data.get_custom_data("should_update"):
            continue
        
        set_cell(cell, -1)
        var cell_data = automation_objects_tilemap.get_cell_tile_data(cell)
        if cell_data != null:
            _update_cell(cell, cell_data)
    
    var rebuild_tiles_time = Time.get_ticks_usec() - start_time
    print_rich("[b]Updated interactable map[/b] in [color=green]%dus[/color] and [b]rebuilt tiles[/b] in [color=green]%dus[/color]" % [update_interactable_map_time, rebuild_tiles_time])

## Re-tiles the cells around the given cell, including the cell itself if it has an automation object.
func update_around(cell: Vector2i):
    var neighbors = automation_zones_tilemap.get_surrounding_cells(cell)
    neighbors.append(cell) # Also update the cell itself
    
    for n in neighbors:
        var zone_data = automation_zones_tilemap.get_cell_tile_data(n)
        if zone_data == null or not zone_data.get_custom_data("should_update"):
            continue
        
        set_cell(cell, -1)

        var cell_data = automation_objects_tilemap.get_cell_tile_data(n)
        if cell_data != null:
            _update_cell(n, cell_data)

const CounterAutotile = preload("res://scripts/automation/counter_autotile.gd")
const BeltAutotile = preload("res://scripts/automation/belt_autotile.gd")

func _update_cell(cell: Vector2i, cell_data: TileData) -> void:
    var meaning = cell_data.get_custom_data("meaning")
    match meaning:
        "counter":
            var interactable = interactable_map.get(cell)
            CounterAutotile.update_counter(cell, cell_data, interactable, automation_objects_tilemap.get_cell_tile_data, set_cell)
        "belt":
            BeltAutotile.update_belt(cell, cell_data, automation_objects_tilemap.get_cell_tile_data, set_cell)
