@tool

extends TileMapLayer

class_name WorldInteractableTilemap

@export var automation_zones_tilemap: AutomationZonesTilemap
@export var automation_objects_tilemap: AutomationObjectsTilemap

@onready var interactables: Node2D = $WorldInteractables

var interactable_map: Dictionary[Vector2i, Node2D] = {}

const COUNTER_TILE_SOURCE_ID = 4
const BELT_TILE_SOURCE_ID = 3

const COUNTER_DOWN_ROW = 0
const COUNTER_UP_ROW = 2
const COUNTER_RIGHT_ROW = 4
const COUNTER_LEFT_ROW = 6

const COUNTER_MACHINE_ROWS: Dictionary[String, int] = {
    "down" = 8,
    "up" = 10,
    "right" = 12,
    "left" = 14
}

# Maps from neighbor belts directed into a belt to atlas position
# Key is in the format (back relative to forward, left relative to forward, right relative to forward) and stored as binary.
# The picked belt also depends on if there's a belt in front of this one (facing any direction),
# but those variants are always offset by half the tile map height so we don't need to separately store them.
# We have 4 maps since Godot doesn't support nested collections :(
const UP_BELT_COMBINATIONS: Dictionary[int, Vector2i] = {
    0b000: Vector2i(0, 5 ), # Start of upward belt
    0b001: Vector2i(0, 9 ), # Left-up corner
    0b010: Vector2i(0, 13), # Right-up corner
    0b011: Vector2i(0, 21), # T-junction (left and right into up)
    0b100: Vector2i(0, 4 ), # Straight up
    0b101: Vector2i(0, 22), # Left and back into up
    0b110: Vector2i(0, 25), # Right and back into up
    0b111: Vector2i(0, 28), # 4-way (left, right, and down into up)
}
const DOWN_BELT_COMBINATIONS: Dictionary[int, Vector2i] = {
    0b000: Vector2i(0, 7 ), # Start of downward belt
    0b001: Vector2i(0, 15), # Right-down corner
    0b010: Vector2i(0, 11), # Left-down corner
    0b011: Vector2i(0, 18), # T-junction (left and right into down)
    0b100: Vector2i(0, 6 ), # Straight down
    0b101: Vector2i(0, 23), # Right and back into down
    0b110: Vector2i(0, 26), # Left and back into down
    0b111: Vector2i(0, 29), # 4-way (left, right, and up into down)
}
const RIGHT_BELT_COMBINATIONS: Dictionary[int, Vector2i] = {
    0b000: Vector2i(0, 1 ), # Start of rightward belt
    0b001: Vector2i(0, 10), # Up-right corner
    0b010: Vector2i(0, 8 ), # Down-right corner
    0b011: Vector2i(0, 27), # T-junction (up and down into right)
    0b100: Vector2i(0, 0 ), # Straight right
    0b101: Vector2i(0, 16), # Down and back into right
    0b110: Vector2i(0, 19), # Up and back into right
    0b111: Vector2i(0, 30), # 4-way (up, down, and left into right)
}
const LEFT_BELT_COMBINATIONS: Dictionary[int, Vector2i] = {
    0b000: Vector2i(0, 3 ), # Start of leftward belt
    0b001: Vector2i(0, 12), # Down-left corner
    0b010: Vector2i(0, 14), # Up-left corner
    0b011: Vector2i(0, 24), # T-junction (up and down into left)
    0b100: Vector2i(0, 2 ), # Straight left
    0b101: Vector2i(0, 20), # Up and back into left
    0b110: Vector2i(0, 17), # Down and back into left
    0b111: Vector2i(0, 31), # 4-way (up, down, and right into left)
}

# :( GDScript nested collections when?
const BELT_COMBINATION_MAPS: Dictionary[String, Variant] = {
    "up": UP_BELT_COMBINATIONS,
    "down": DOWN_BELT_COMBINATIONS,
    "right": RIGHT_BELT_COMBINATIONS,
    "left": LEFT_BELT_COMBINATIONS,
}

const BELT_ANIMATION_FRAMES: int = 8

func _ready():
    # Populate tile map with what's in the world so we can easily set things up in the editor;
    # future changes will be manually handled instead of from scratch
    
    _update_interactable_map()

func _update_interactable_map():
    interactable_map.clear()
    for child in interactables.get_children():
        interactable_map[_get_tilemap_pos(child.get_node("InteractableContent").global_position)] = child

func _get_tilemap_pos(global_pos: Vector2) -> Vector2i:
    return local_to_map(to_local(global_pos))

@export_tool_button("Add missing counter interactables") var add_missing_counters = _add_missing_counters
@export_tool_button("Delete autogenerated interactables") var delete_autogenerated = _delete_autogenerated

const TableSurfaceInteractable = preload("res://world/interactable/TableSurfaceInteractable.tscn")

func _add_missing_counters():
    _update_interactable_map()

    # For every counter tile that doesn't have an interactable on it, add a blank counter one.
    for cell in automation_objects_tilemap.get_used_cells():
        var cell_data = automation_objects_tilemap.get_cell_tile_data(cell)
        if cell_data == null or cell_data.get_custom_data("meaning") != "counter":
            continue
        
        if interactable_map.has(cell):
            continue
        
        var counter_instance = TableSurfaceInteractable.instantiate()
        counter_instance.name = "!Counter_%d_%d" % [cell.x, cell.y]
        interactables.add_child(counter_instance)
        counter_instance.position = automation_objects_tilemap.map_to_local(cell)
        counter_instance.owner = get_tree().edited_scene_root
        interactable_map[cell] = counter_instance

func _delete_autogenerated():
    for child in interactables.get_children():
        if child.name.begins_with("!"):
            child.queue_free()
    
    _update_interactable_map.call_deferred()

@export_tool_button("Rebuild tiles") var rebuild_tiles = _rebuild_tiles

func xnor(a: bool, b: bool) -> bool:
    return (a and b) or (not a and not b)

func _rebuild_tiles():
    var start_time = Time.get_ticks_usec()
    
    _update_interactable_map()

    var update_interactable_map_time = Time.get_ticks_usec() - start_time
    start_time = Time.get_ticks_usec()

    # Clear all tiles in the automation zones
    var used_cells = automation_zones_tilemap.get_used_cells()

    # Clear all cells in automation zones, since we'll rebuild all of them
    for cell in used_cells:
        var zone_data = automation_zones_tilemap.get_cell_tile_data(cell)
        if not zone_data.get_custom_data("should_update"):
            continue
        
        set_cell(cell, -1)
        var cell_data = automation_objects_tilemap.get_cell_tile_data(cell)
        if cell_data != null:
            _update_cell(cell, cell_data)
    
    var rebuild_tiles_time = Time.get_ticks_usec() - start_time
    print_rich("[b]Updated interactable map[/b] in [color=green]%dus[/color] and [b]rebuilt tiles[/b] in [color=green]%dus[/color]" % [update_interactable_map_time, rebuild_tiles_time])

## Re-tiles the cells around the given cell, including the cell itself if it has an automation object.
func update_around(cell: Vector2i):
    var neighbors = automation_zones_tilemap.get_surrounding_cells(cell)
    neighbors.append(cell) # Also update the cell itself
    
    for n in neighbors:
        var zone_data = automation_zones_tilemap.get_cell_tile_data(n)
        if zone_data == null or not zone_data.get_custom_data("should_update"):
            continue
        
        set_cell(cell, -1)

        var cell_data = automation_objects_tilemap.get_cell_tile_data(n)
        if cell_data != null:
            _update_cell(n, cell_data)

func _update_cell(cell: Vector2i, cell_data: TileData) -> void:
    var meaning = cell_data.get_custom_data("meaning")
    match meaning:
        "counter":
            _update_counter(cell, cell_data)
        "belt":
            _update_belt(cell, cell_data)

func _update_counter(pos: Vector2i, cell_data: TileData):
    var left_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.LEFT)
    var right_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.RIGHT)
    var up_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.UP)

    var counter_left: bool = left_data and left_data.get_custom_data("is_counter_like")
    var counter_right: bool = right_data and right_data.get_custom_data("is_counter_like")
    var counter_up: bool = up_data and up_data.get_custom_data("is_counter_like")

    var direction: String = cell_data.get_custom_data("facing")

    var interactable = interactable_map.get(pos)
    var machine = null
    if interactable != null:
        machine = interactable.get("machine")

    if machine != null:
        var tile_x = machine.custom_counter_x
        if tile_x != null and tile_x >= 0:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(tile_x, COUNTER_MACHINE_ROWS[direction]))
            return
    
    if direction == "down":
        if xnor(counter_left, counter_right):
            var variant = hash(pos + Vector2i(200, 0)) % 2
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(variant, COUNTER_DOWN_ROW))
        elif counter_left:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(2, COUNTER_DOWN_ROW))
        else:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(3, COUNTER_DOWN_ROW))
    elif direction == "up":
        if xnor(counter_left, counter_right):
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(0, COUNTER_UP_ROW))
        elif counter_left:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(1, COUNTER_UP_ROW))
        else:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(2, COUNTER_UP_ROW))
    elif direction == "right":
        var counter_right_facing_down = counter_right and right_data.get_custom_data("facing") == "down"
        var counter_right_facing_up = counter_right and right_data.get_custom_data("facing") == "up"
        if counter_up and counter_right_facing_down:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(2, COUNTER_RIGHT_ROW))
        elif counter_right_facing_down:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(1, COUNTER_RIGHT_ROW))
        else:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(0, COUNTER_RIGHT_ROW))
    elif direction == "left":
        if counter_up and counter_left:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(2, COUNTER_LEFT_ROW))
        elif counter_left:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(1, COUNTER_LEFT_ROW))
        else:
            set_cell(pos, COUNTER_TILE_SOURCE_ID, Vector2i(0, COUNTER_LEFT_ROW))

func _update_belt(pos: Vector2i, cell_data: TileData):
    var up_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.UP)
    var bottom_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.DOWN)
    var left_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.LEFT)
    var right_data = automation_objects_tilemap.get_cell_tile_data(pos + Vector2i.RIGHT)

    var top_belt = up_data != null and up_data.get_custom_data("meaning") == "belt"
    var bottom_belt = bottom_data != null and bottom_data.get_custom_data("meaning") == "belt"
    var left_belt = left_data != null and left_data.get_custom_data("meaning") == "belt"
    var right_belt = right_data != null and right_data.get_custom_data("meaning") == "belt"

    var top_facing_into = top_belt and up_data.get_custom_data("facing") == "down"
    var bottom_facing_into = bottom_belt and bottom_data.get_custom_data("facing") == "up"
    var left_facing_into = left_belt and left_data.get_custom_data("facing") == "right"
    var right_facing_into = right_belt and right_data.get_custom_data("facing") == "left"

    var direction: String = cell_data.get_custom_data("facing")

    var back: bool = false
    var left: bool = false
    var right: bool = false
    var front: bool = false
    match direction:
        "up":
            back = bottom_facing_into
            left = left_facing_into
            right = right_facing_into
            front = top_belt
        "down":
            back = top_facing_into
            left = right_facing_into
            right = left_facing_into
            front = bottom_belt
        "right":
            back = left_facing_into
            left = top_facing_into
            right = bottom_facing_into
            front = right_belt
        "left":
            back = right_facing_into
            left = bottom_facing_into
            right = top_facing_into
            front = left_belt
    
    var atlas_pos = BELT_COMBINATION_MAPS[direction][(int(back) << 2) | (int(left) << 1) | int(right)]
    if not front:
        atlas_pos.x += BELT_ANIMATION_FRAMES
    set_cell(pos, BELT_TILE_SOURCE_ID, atlas_pos)
